name: AllUni CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        
    - name: Run tests
      run: |
        cd AllUni
        pipenv run python manage.py test
        
    - name: Run coverage
      run: |
        cd AllUni
        pipenv run coverage run --source='.' manage.py test
        pipenv run coverage report
        pipenv run coverage html
        
      # O coverage report ele é tipo o html mas em tempo real
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: AllUni/htmlcov/ # é o report E o html
        
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Containerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/alluni:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/alluni:${{ github.sha }}
        
    - name: Generate static site for GitHub Pages
      run: |
        mkdir -p _site
        cp -r AllUni/htmlcov/* _site/
        echo "<html><head><meta http-equiv=\"refresh\" content=\"0; url=index.html\"></head></html>" > _site/index.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
